### ISSUE TITLE
Fix the "No space left on device" issue when trying to upload large packages

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/archivematica-infra#128]
While trying to upload a large package to Archivematica (~34GB), we saw an issue where the package never appeared in the dashboard, and instead we saw an error in the logs for the Archivematica storage service container:

```
OSError: [Errno 28] No space left on device
```

<details><summary>Full stack trace</summary>

```
File "/src/storage_service/locations/api/resources.py", line 652, in _handle_location_file_move
    return move_files_fn(data["files"], origin_location, destination_location)
File "/src/storage_service/locations/api/resources.py", line 673, in move_files
    async_task = AsyncManager.run_task(task)
Traceback (most recent call last):
File "/src/storage_service/locations/api/resources.py", line 561, in _move_files_between_locations
    raise PosixMoveUnsupportedError
locations.models.space.PosixMoveUnsupportedError
(empty)
During handling of the above exception, another exception occurred:
(empty)
Traceback (most recent call last):
File "/src/storage_service/locations/models/async_manager.py", line 140, in wrapper
    value = task_fn(*args, **kwargs)
File "/src/storage_service/locations/api/resources.py", line 669, in task
    files, origin_location, destination_location
File "/usr/local/lib/python3.6/dist-packages/q.py", line 304, in wrapper
    result = func(*args, **kwargs)
File "/src/storage_service/locations/api/resources.py", line 575, in _move_files_between_locations
    destination_space=destination_space,
File "/src/storage_service/locations/models/space.py", line 366, in move_to_storage_service
    source_path, destination_path, destination_space, *args, **kwargs
File "/usr/local/lib/python3.6/dist-packages/q.py", line 304, in wrapper
    result = func(*args, **kwargs)
File "/src/storage_service/locations/models/s3.py", line 231, in move_to_storage_service
    bucket.download_file(objectSummary.key, dest_file)
File "/usr/local/lib/python3.6/dist-packages/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
File "/usr/local/lib/python3.6/dist-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
File "/usr/local/lib/python3.6/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
File "/usr/local/lib/python3.6/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
File "/usr/local/lib/python3.6/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
File "/usr/local/lib/python3.6/dist-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
File "/usr/local/lib/python3.6/dist-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
File "/usr/local/lib/python3.6/dist-packages/s3transfer/download.py", line 572, in _main
    fileobj.write(data)
File "/usr/local/lib/python3.6/dist-packages/s3transfer/utils.py", line 364, in write
    self._fileobj.write(data)
OSError: [Errno 28] No space left on device
ERROR     2023-04-12 10:17:23  locations.models.async_manager:async_manager:wrapper:143:  Task threw an error: [Errno 28] No space left on device
Caller's traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 155, in handle
    super(GeventWorker, self).handle(listener, client, addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/whitenoise/middleware.py", line 25, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/tastypie/resources.py", line 227, in wrapper
    response = callback(request, *args, **kwargs)
File "/src/storage_service/locations/api/resources.py", line 208, in wrapper
    result = func(resource, request, bundle, **kwargs)
File "/src/storage_service/locations/api/resources.py", line 687, in post_detail_async
    return self._handle_location_file_move(move_files, request, *args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/q.py", line 304, in wrapper
    result = func(*args, **kwargs)
```

</details>

This is preventing us from storing the package.

**Comment by alexwlchan** [comment]
To investigate this issue, I ssh'd into the Archivematica container host and ran `df -h` to see the available disk space:

```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         16G     0   16G   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G  2.1M   16G   1% /run
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/nvme0n1p1   30G  9.6G   20G  33% /
/dev/nvme1n1    2.0T   70G  1.8T   4% /ebs
tmpfs           3.1G     0  3.1G   0% /run/user/1000
```

When I uploaded the package, I noticed the disk used on `/` was increasing – but we have a large EBS volume mounted at `/ebs` which is meant to be where working data is being stored. What's up with that?

**Comment by alexwlchan** [comment]
This does expose a couple of things I'm going to change:

* Despite configuring a 2TB EBS volume for large package storage, we haven't been using it for months – all our packages have been fitting within the ~20GB of instance storage. I'm going to reduce the size of the EBS volume and save a bit of money.
* While looking at that, I realise our RDS instances are probably (still) overprovisioned – newer versions of Archivematica are much more efficient with database connections, so I think we can drop another instance size. This takes us from 90 to 45 max connections; in the last month our max connections are usually less than 40, so I think we can try turning down further.

**Comment by alexwlchan** [comment]
It turns out this issue was also affecting staging, so I've fixed it there too.
