### ISSUE TITLE
Dashboard can't connect to the storage service

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/archivematica-infra#18]
These are the logs from the dashboard container:

```
WARNING   2019-01-11 14:35:47  archivematica.common:storageService:get_pipeline:131:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2019-01-11 14:35:47  archivematica.common:storageService:get_pipeline:134:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 132, in get_pipeline
    response.raise_for_status()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://am-storage-service.archivematica:8000/api/v2/pipeline/173dea95-c429-47b2-8f8f-8038cf55261b/
WARNING   2019-01-11 14:35:47  archivematica.dashboard:steps:setup_pipeline_in_ss:82:  SS inaccessible or pipeline not registered.
INFO      2019-01-11 14:35:47  archivematica.common:storageService:create_pipeline:115:  Creating pipeline in storage service with {'remote_name': u'http://localhost:9000', 'api_key': u'test', 'uuid': u'173dea95-c429-47b2-8f8f-8038cf55261b', 'shared_path': '/var/archivematica/sharedDirectory/', 'api_username': u'test', 'create_default_locations': True, 'description': 'Archivematica on ip-10-50-3-140.eu-west-1.compute.internal'}
DEBUG     2019-01-11 14:41:33  archivematica.common:storageService:get_location:177:  Storage locations returned: [{u'uuid': u'feeb08fb-35fe-412e-8905-7d0c37bf90d3', u'pipeline': [u'/api/v2/pipeline/173dea95-c429-47b2-8f8f-8038cf55261b/'], u'used': u'0', u'description': u'', u'space': u'/api/v2/space/82782136-6610-44cc-876d-d8135b43e805/', u'enabled': True, u'quota': None, u'relative_path': u'home', u'purpose': u'TS', u'path': u'/home', u'resource_uri': u'/api/v2/location/feeb08fb-35fe-412e-8905-7d0c37bf90d3/'}]
```

Running a curl by hand, it looks like service discovery is working, but we're getting a 401 from the storage service:

```console
root@ip-10-50-3-140:/var/log/archivematica/dashboard# curl -v http://am-storage-service.archivematica:8000/api/v2/pipeline/173dea95-c429-47b2-8f8f-8038cf55261b/
*   Trying 10.50.3.221...
* TCP_NODELAY set
* Connected to am-storage-service.archivematica (10.50.3.221) port 8000 (#0)
> GET /api/v2/pipeline/173dea95-c429-47b2-8f8f-8038cf55261b/ HTTP/1.1
> Host: am-storage-service.archivematica:8000
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 401 UNAUTHORIZED
< Server: gunicorn/19.9.0
< Date: Fri, 11 Jan 2019 14:44:30 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< Vary: Accept-Language, Cookie
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/html; charset=utf-8
< WWW-Authenticate: Basic Realm="django-tastypie"
< Content-Language: en
<
* Connection #0 to host am-storage-service.archivematica left intact
```

**Comment by alexwlchan** [comment]
That seemed to be fixed by running

```
/usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python   /usr/share/archivematica/dashboard/manage.py     install       --username="test"       --password="test"       --email="test@test.com"       --org-name="test"       --org-id="test"       --api-key="test"       --ss-url="$WELLCOME_SS_URL"       --ss-user="test"       --ss-api-key="test" --site-url="http://am-dashboard.archivematica:9000"
```

Next error:

```
ERROR     2019-01-11 14:52:33  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /backlog/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/archivematica/dashboard/components/backlog/views.py", line 90, in execute
    es_client = elasticSearchFunctions.get_client()
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 154, in get_client
    create_indexes_if_needed(_es_client)  # TODO: find a better place!
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 199, in create_indexes_if_needed
    create_aips_index(client)
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 204, in create_aips_index
    create_index(client, 'aips')
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 270, in create_index
    response = client.indices.create(index, ignore=400)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 103, in create
    params=params, body=body)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError((<urllib3.connection.HTTPConnection object at 0x7fe0ddf7f090>, u'Connection to vpc-archivematica-djfzdylo2mxnepfkdzozycqgiq.eu-west-1.es.amazonaws.com timed out. (connect timeout=10.0)')) caused by: ConnectTimeoutError((<urllib3.connection.HTTPConnection object at 0x7fe0ddf7f090>, u'Connection to vpc-archivematica-djfzdylo2mxnepfkdzozycqgiq.eu-west-1.es.amazonaws.com timed out. (connect timeout=10.0)'))
```

And testing with curl:

```
root@ip-10-50-3-140:/# curl 'vpc-archivematica-djfzdylo2mxnepfkdzozycqgiq.eu-west-1.es.amazonaws.com'
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}root@ip-10-50-3-140:/#
```

So looks like we need some Elasticsearch auth.

**Comment by alexwlchan** [comment]
I think this might be the next error along:

```
ERROR     2019-01-11 16:13:27  django.request:base:handle_uncaught_exception:256:  Internal Server Error: /transfer/status/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/middleware/locale.py", line 32, in process_request
    request, check_path=check_path)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 198, in get_language_from_request
    return _trans.get_language_from_request(request, check_path)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 503, in get_language_from_request
    lang_code = request.session.get(LANGUAGE_SESSION_KEY)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 59, in get
    return self._session.get(key, default)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 181, in _get_session
    self._session_cache = self.load()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 21, in load
    expire_date__gt=timezone.now()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 387, in as_sql
    where, w_params = self.compile(self.query.where)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 357, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/where.py", line 104, in as_sql
    sql, params = compiler.compile(child)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 357, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 218, in as_sql
    lhs_sql, params = self.process_lhs(compiler, connection)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 211, in process_lhs
    db_type = self.lhs.output_field.db_type(connection=connection)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1040, 'Too many connections')
```

RDS itself hasn't maxed its connection limit, so this must be something else.

**Comment by alexwlchan** [comment]
More notes: I’ve noticed the dashboard making lots of requests to `/status/?<timestamp>`.

Following the code a bit in the Archivematica repo, and trying it inside the live dashboard container, it looks like it’s submitting a request to Gearman that never responds.

Specifically, it sends off a `getJobsAwaitingApproval` job, which the MPC server is meant to respond to, and it seemingly doesn't.

<details>
<summary>Debugging session output</summary>

```pycon
>>> from contrib.mcp.client import MCPClient
c>>> client = MCPClient()
>>> client.list()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "contrib/mcp/client.py", line 151, in list
    completed_job_request = gm_client.submit_job("getJobsAwaitingApproval", "", None)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 37, in submit_job
    completed_job_list = self.submit_multiple_jobs([job_info], background=background, wait_until_complete=wait_until_complete, max_retries=max_retries, poll_timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 50, in submit_multiple_jobs
    return self.submit_multiple_requests(requests_to_submit, wait_until_complete=wait_until_complete, poll_timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 70, in submit_multiple_requests
    processed_requests = self.wait_until_jobs_completed(processed_requests, poll_timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 114, in wait_until_jobs_completed
    self.poll_connections_until_stopped(self.connection_list, continue_while_jobs_incomplete, timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 193, in poll_connections_until_stopped
    read_connections, write_connections, dead_connections = self.poll_connections_once(submitted_connections, timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 128, in poll_connections_once
    rd_list, wr_list, ex_list = gearman.util.select(check_rd_connections, check_wr_connections, select_connections, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/util.py", line 61, in select
    rd_list, wr_list, ex_list = select_lib.select(*select_args)
KeyboardInterrupt
>>> import gearman
>>> gm_client = gearman.GearmanClient([client.server])
>>> completed_job_request = gm_client.submit_job("getJobsAwaitingApproval", "", None)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 37, in submit_job
    completed_job_list = self.submit_multiple_jobs([job_info], background=background, wait_until_complete=wait_until_complete, max_retries=max_retries, poll_timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 50, in submit_multiple_jobs
    return self.submit_multiple_requests(requests_to_submit, wait_until_complete=wait_until_complete, poll_timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 70, in submit_multiple_requests
    processed_requests = self.wait_until_jobs_completed(processed_requests, poll_timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 114, in wait_until_jobs_completed
    self.poll_connections_until_stopped(self.connection_list, continue_while_jobs_incomplete, timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 193, in poll_connections_until_stopped
    read_connections, write_connections, dead_connections = self.poll_connections_once(submitted_connections, timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 128, in poll_connections_once
    rd_list, wr_list, ex_list = gearman.util.select(check_rd_connections, check_wr_connections, select_connections, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/util.py", line 61, in select
    rd_list, wr_list, ex_list = select_lib.select(*select_args)
KeyboardInterrupt
>>> job_info = {"task": "getJobsAwaitingApproval", data="", unique=None, priority=
KeyboardInterrupt
>>> from gearman.constants import PRIORITY_NONE
>>> job_info = {"task": "getJobsAwaitingApproval", data="", unique=None, priority=PRIORITY_NONE}
  File "<stdin>", line 1
    job_info = {"task": "getJobsAwaitingApproval", data="", unique=None, priority=PRIORITY_NONE}
                                                       ^
SyntaxError: invalid syntax
>>> job_info = {"task": "getJobsAwaitingApproval", data:"", unique=None, priority=PRIORITY_NONE}
  File "<stdin>", line 1
    job_info = {"task": "getJobsAwaitingApproval", data:"", unique=None, priority=PRIORITY_NONE}
                                                                  ^
SyntaxError: invalid syntax
>>> job_info = {"task": "getJobsAwaitingApproval", data:"", None, priority=PRIORITY_NONE}
  File "<stdin>", line 1
    job_info = {"task": "getJobsAwaitingApproval", data:"", None, priority=PRIORITY_NONE}
                                                                ^
SyntaxError: invalid syntax
>>> job_info = {"task": "getJobsAwaitingApproval", data:"", None, "priority":PRIORITY_NONE}
  File "<stdin>", line 1
    job_info = {"task": "getJobsAwaitingApproval", data:"", None, "priority":PRIORITY_NONE}
                                                                ^
SyntaxError: invalid syntax
>>> job_info = {"task": "getJobsAwaitingApproval", data:"", "unique":None, "priority":PRIORITY_NONE}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
>>> job_info = {"task": "getJobsAwaitingApproval", data":"", "unique":None, "priority":PRIORITY_NONE}
  File "<stdin>", line 1
    job_info = {"task": "getJobsAwaitingApproval", data":"", "unique":None, "priority":PRIORITY_NONE}
                                                         ^
SyntaxError: invalid syntax
>>> job_info = {"task": "getJobsAwaitingApproval", "data":"", "unique":None, "priority":PRIORITY_NONE}
>>> completed_job_list = gm_client.submit_multiple_jobs([job_info], background=False, wait_until_complete=True,max_retries=0,poll_timeout=None)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 50, in submit_multiple_jobs
    return self.submit_multiple_requests(requests_to_submit, wait_until_complete=wait_until_complete, poll_timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 70, in submit_multiple_requests
    processed_requests = self.wait_until_jobs_completed(processed_requests, poll_timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 114, in wait_until_jobs_completed
    self.poll_connections_until_stopped(self.connection_list, continue_while_jobs_incomplete, timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 193, in poll_connections_until_stopped
    read_connections, write_connections, dead_connections = self.poll_connections_once(submitted_connections, timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 128, in poll_connections_once
    rd_list, wr_list, ex_list = gearman.util.select(check_rd_connections, check_wr_connections, select_connections, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/util.py", line 61, in select
    rd_list, wr_list, ex_list = select_lib.select(*select_args)
KeyboardInterrupt
>>> requests_to_submit = [gm_client._create_request_from_dictionary([job_info], background=False, wait_until_complete=True,max_retries=0,poll_timeout=None)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: _create_request_from_dictionary() got an unexpected keyword argument 'wait_until_complete'
>>> requests_to_submit = [gm_client._create_request_from_dictionary([job_info], background=False, max_retries=0)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 169, in _create_request_from_dictionary
    job_unique = job_info.get('unique')
AttributeError: 'list' object has no attribute 'get'
>>> requests_to_submit = [gm_client._create_request_from_dictionary(job_info, background=False, max_retries=0)]
>>> requests_to_submit
[<GearmanJobRequest task='getJobsAwaitingApproval', unique='b5e2249a4d60273dac5779d8696003dd', priority=None, background=False, state='UNKNOWN', timed_out=False>]
>>> gm_client.submit_multiple_requests(requests_to_submit, wait-until_complete=True, poll_timeout=None)
  File "<stdin>", line 1
SyntaxError: keyword can't be an expression
>>> gm_client.submit_multiple_requests(requests_to_submit, wait_until_complete=True, poll_timeout=None)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 70, in submit_multiple_requests
    processed_requests = self.wait_until_jobs_completed(processed_requests, poll_timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/client.py", line 114, in wait_until_jobs_completed
    self.poll_connections_until_stopped(self.connection_list, continue_while_jobs_incomplete, timeout=poll_timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 193, in poll_connections_until_stopped
    read_connections, write_connections, dead_connections = self.poll_connections_once(submitted_connections, timeout=time_remaining)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/connection_manager.py", line 128, in poll_connections_once
    rd_list, wr_list, ex_list = gearman.util.select(check_rd_connections, check_wr_connections, select_connections, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/gearman/util.py", line 61, in select
    rd_list, wr_list, ex_list = select_lib.select(*select_args)
KeyboardInterrupt
>>> gm_client.submit_multiple_requests(requests_to_submit, wait_until_complete=True, poll_timeout=1.0)
[<GearmanJobRequest task='getJobsAwaitingApproval', unique='b5e2249a4d60273dac5779d8696003dd', priority=None, background=False, state='CREATED', timed_out=True>]
>>> gm_client.submit_multiple_requests(requests_to_submit, wait_until_complete=True, poll_timeout=None)
```
</details>
